# Generated by Django 3.0.11 on 2020-12-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='Company',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
